// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherApp.Data;

namespace WeatherApp.Data.Migrations
{
    [DbContext(typeof(WeatherAppDbContext))]
    [Migration("20190822161740_AddedCityForecasts")]
    partial class AddedCityForecasts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("WeatherApp.Domain.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("WeatherApp.Domain.CityForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityName");

                    b.Property<DateTime>("Date");

                    b.Property<double>("Humidity");

                    b.Property<double>("Temperature");

                    b.HasKey("Id");

                    b.ToTable("CityForecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
